export const CURRENCY_LABEL = {
  'CAD': 'Dólar canadense',
  'HKD': 'Dólar de Hong Kong',
  'ISK': 'Coroa islandesa',
  'PHP': 'Peso filipino',
  'DKK': 'Coroa dinamarquesa',
  'HUF': 'Florim húngaro',
  'CZK': 'Coroa tcheca',
  'GBP': 'Libra esterlina',
  'RON': 'Leu romeno',
  'SEK': 'Coroa sueca',
  'IDR': 'Rupia indonésia',
  'INR': 'Rupia indiana',
  'BRL': 'Real brasileiro',
  'RUB': 'Rublo russo',
  'HRK': 'Kuna croata',
  'JPY': 'Lene japonês',
  'THB': 'Baht tailandês',
  'CHF': 'Franco suíço',
  'EUR': 'Euro',
  'MYR': 'Ringgit malaio',
  'BGN': 'Lev búlgaro',
  'TRY': 'Lira turca',
  'CNY': 'Remimbi',
  'NOK': 'Coroa norueguesa',
  'NZD': 'Dólar neozelandês',
  'ZAR': 'Rand sul-africano',
  'USD': 'Dólar americano',
  'MXN': 'Peso mexicano',
  'SGD': 'Dólar singapuriano',
  'AUD': 'Dólar australiano',
  'ILS': 'Novo shekel israelense',
  'KRW': 'Won sul-coreano',
  'PLN': 'Zloty polonês',
}
