import { translate } from '../locales'

export const CURRENCY_LABEL = {
  'CAD': translate('currencies.CAD'),
  'HKD': translate('currencies.HKD'),
  'ISK': translate('currencies.ISK'),
  'PHP': translate('currencies.PHP'),
  'DKK': translate('currencies.DKK'),
  'HUF': translate('currencies.HUF'),
  'CZK': translate('currencies.CZK'),
  'GBP': translate('currencies.GBP'),
  'RON': translate('currencies.RON'),
  'SEK': translate('currencies.SEK'),
  'IDR': translate('currencies.IDR'),
  'INR': translate('currencies.INR'),
  'BRL': translate('currencies.BRL'),
  'RUB': translate('currencies.RUB'),
  'HRK': translate('currencies.HRK'),
  'JPY': translate('currencies.JPY'),
  'THB': translate('currencies.THB'),
  'CHF': translate('currencies.CHF'),
  'EUR': translate('currencies.EUR'),
  'MYR': translate('currencies.MYR'),
  'BGN': translate('currencies.BGN'),
  'TRY': translate('currencies.TRY'),
  'CNY': translate('currencies.CNY'),
  'NOK': translate('currencies.NOK'),
  'NZD': translate('currencies.NZD'),
  'ZAR': translate('currencies.ZAR'),
  'USD': translate('currencies.USD'),
  'MXN': translate('currencies.MXN'),
  'SGD': translate('currencies.SGD'),
  'AUD': translate('currencies.AUD'),
  'ILS': translate('currencies.ILS'),
  'KRW': translate('currencies.KRW'),
  'PLN': translate('currencies.PLN'),
}
